const status = (options) => ({ key: 'status', label: 'Statut', type: 'select', required: true, options });

export const modules = {
    users: {
        title: 'Utilisateurs & rôles', singular: 'utilisateur', endpoint: '/users', search: 'nom, identifiant ou e-mail',
        columns: [['name', 'Nom'], ['login', 'Identifiant'], ['email', 'E-mail'], ['role.name', 'Rôle'], ['is_active', 'Actif']],
        fields: [
            { key: 'name', label: 'Nom complet', required: true }, { key: 'login', label: 'Identifiant', required: true },
            { key: 'email', label: 'E-mail', type: 'email', required: true },
            { key: 'role_id', label: 'Rôle', type: 'select', required: true, options: [] },
            { key: 'password', label: 'Mot de passe', type: 'password' },
            { key: 'password_confirmation', label: 'Confirmation', type: 'password' },
            { key: 'is_active', label: 'Compte actif', type: 'checkbox' },
        ],
        defaults: { role_id: '', is_active: true },
    },
    clients: {
        title: 'Clients', singular: 'client', endpoint: '/clients', search: 'nom, e-mail, téléphone ou société',
        columns: [['name', 'Nom'], ['company', 'Société'], ['email', 'E-mail'], ['phone', 'Téléphone'], ['status', 'Statut']],
        fields: [
            { key: 'name', label: 'Nom', required: true }, { key: 'company', label: 'Société' },
            { key: 'email', label: 'E-mail', type: 'email' }, { key: 'phone', label: 'Téléphone' },
            { key: 'city', label: 'Ville' }, status([{ value: 'active', label: 'Actif' }, { value: 'inactive', label: 'Inactif' }]),
            { key: 'notes', label: 'Notes', type: 'textarea', wide: true },
        ],
        defaults: { status: 'active' },
    },
    leads: {
        title: 'Prospects', singular: 'prospect', endpoint: '/leads', search: 'nom, société ou source',
        columns: [['name', 'Nom'], ['company', 'Société'], ['source', 'Source'], ['value', 'Valeur (DT)'], ['status', 'Étape']],
        fields: [
            { key: 'name', label: 'Nom', required: true }, { key: 'company', label: 'Société' },
            { key: 'email', label: 'E-mail', type: 'email' }, { key: 'phone', label: 'Téléphone' },
            { key: 'source', label: 'Source' }, { key: 'value', label: 'Valeur estimée', type: 'number' },
            status([{ value: 'new', label: 'Nouveau' }, { value: 'contacted', label: 'Contacté' }, { value: 'qualified', label: 'Qualifié' }, { value: 'converted', label: 'Converti' }, { value: 'lost', label: 'Perdu' }]),
            { key: 'notes', label: 'Notes', type: 'textarea', wide: true },
        ],
        defaults: { status: 'new', value: 0 },
    },
    quotes: {
        title: 'Devis', singular: 'devis', endpoint: '/quotes', search: 'référence',
        columns: [['reference', 'Référence'], ['client.name', 'Client'], ['total', 'Total (DT)'], ['valid_until', 'Validité'], ['status', 'Statut']],
        fields: [
            { key: 'reference', label: 'Référence', required: true }, { key: 'client_id', label: 'ID client', type: 'number', required: true },
            { key: 'subtotal', label: 'Sous-total', type: 'number', required: true }, { key: 'tax', label: 'Taxes', type: 'number' },
            { key: 'total', label: 'Total', type: 'number', required: true }, { key: 'valid_until', label: 'Valide jusqu’au', type: 'date' },
            status([{ value: 'draft', label: 'Brouillon' }, { value: 'sent', label: 'Envoyé' }, { value: 'accepted', label: 'Accepté' }, { value: 'rejected', label: 'Refusé' }]),
            { key: 'notes', label: 'Notes', type: 'textarea', wide: true },
        ],
        defaults: { status: 'draft', subtotal: 0, tax: 0, total: 0 },
    },
    tasks: {
        title: 'Tâches & agenda', singular: 'tâche', endpoint: '/tasks', search: 'titre ou description',
        columns: [['title', 'Titre'], ['priority', 'Priorité'], ['due_at', 'Échéance'], ['assignee.name', 'Assignée à'], ['status', 'Statut']],
        fields: [
            { key: 'title', label: 'Titre', required: true },
            status([{ value: 'todo', label: 'À faire' }, { value: 'in_progress', label: 'En cours' }, { value: 'done', label: 'Terminée' }, { value: 'cancelled', label: 'Annulée' }]),
            { key: 'priority', label: 'Priorité', type: 'select', required: true, options: [{ value: 'low', label: 'Basse' }, { value: 'normal', label: 'Normale' }, { value: 'high', label: 'Haute' }, { value: 'urgent', label: 'Urgente' }] },
            { key: 'due_at', label: 'Échéance', type: 'datetime-local' },
            { key: 'description', label: 'Description', type: 'textarea', wide: true },
        ],
        defaults: { status: 'todo', priority: 'normal' },
    },
    'blog-posts': {
        title: 'Articles du blog', singular: 'article', endpoint: '/blog-posts', search: 'titre ou contenu',
        columns: [['title', 'Titre'], ['category', 'Catégorie'], ['author.name', 'Auteur'], ['published_at', 'Publication'], ['status', 'Statut']],
        fields: [
            { key: 'title', label: 'Titre', required: true }, { key: 'slug', label: 'Slug', required: true },
            { key: 'category', label: 'Catégorie' },
            { key: 'excerpt', label: 'Extrait', type: 'textarea', wide: true }, { key: 'content', label: 'Contenu', type: 'textarea', wide: true },
            { key: 'tags', label: 'Tags (un par ligne)', type: 'list', wide: true },
            { key: 'hero_image', label: 'Image de couverture' },
            { key: 'meta_title', label: 'Titre SEO' }, { key: 'meta_description', label: 'Description SEO', type: 'textarea', wide: true },
            { key: 'canonical_url', label: 'URL canonique', type: 'url', wide: true },
            { key: 'og_title', label: 'Titre Open Graph' }, { key: 'og_description', label: 'Description Open Graph', type: 'textarea', wide: true },
            { key: 'og_image', label: 'Image Open Graph', type: 'url', wide: true },
            { key: 'robots', label: 'Indexation', type: 'select', required: true, options: [{ value: 'index,follow', label: 'Indexer et suivre' }, { value: 'index,nofollow', label: 'Indexer sans suivre' }, { value: 'noindex,follow', label: 'Ne pas indexer, suivre' }, { value: 'noindex,nofollow', label: 'Ne pas indexer' }] },
            status([{ value: 'draft', label: 'Brouillon' }, { value: 'published', label: 'Publié' }]),
            { key: 'published_at', label: 'Date de publication', type: 'datetime-local' }, { key: 'featured', label: 'Mis en avant', type: 'checkbox' },
            { key: 'sort_order', label: 'Ordre', type: 'number' },
        ],
        defaults: { status: 'draft', featured: false, sort_order: 0, tags: '', robots: 'index,follow' },
    },
    solutions: {
        title: 'Solutions métier', singular: 'solution', endpoint: '/solutions', search: 'titre ou description',
        columns: [['title', 'Titre'], ['category', 'Catégorie'], ['featured', 'Mise en avant'], ['sort_order', 'Ordre'], ['status', 'Statut']],
        fields: [
            { key: 'title', label: 'Titre', required: true }, { key: 'slug', label: 'Slug', required: true },
            { key: 'category', label: 'Famille d’activité' },
            { key: 'short_description', label: 'Description courte', type: 'textarea', wide: true },
            { key: 'description', label: 'Description complète', type: 'textarea', wide: true },
            { key: 'problem', label: 'Problème métier', type: 'textarea', wide: true },
            { key: 'value_proposition', label: 'Proposition de valeur', type: 'textarea', wide: true },
            { key: 'modules', label: 'Modules (un par ligne)', type: 'list', wide: true },
            { key: 'benefits', label: 'Bénéfices (un par ligne)', type: 'list', wide: true },
            { key: 'tags', label: 'Tags (un par ligne)', type: 'list', wide: true },
            { key: 'hero_image', label: 'Image de couverture' },
            { key: 'meta_title', label: 'Titre SEO' }, { key: 'meta_description', label: 'Description SEO', type: 'textarea', wide: true },
            { key: 'canonical_url', label: 'URL canonique', type: 'url', wide: true },
            { key: 'og_title', label: 'Titre Open Graph' }, { key: 'og_description', label: 'Description Open Graph', type: 'textarea', wide: true },
            { key: 'og_image', label: 'Image Open Graph', type: 'url', wide: true },
            { key: 'robots', label: 'Indexation', type: 'select', required: true, options: [{ value: 'index,follow', label: 'Indexer et suivre' }, { value: 'noindex,nofollow', label: 'Ne pas indexer' }] },
            status([{ value: 'draft', label: 'Brouillon' }, { value: 'published', label: 'Publié' }]),
            { key: 'featured', label: 'Mise en avant', type: 'checkbox' }, { key: 'sort_order', label: 'Ordre', type: 'number' },
        ],
        defaults: { status: 'draft', featured: false, sort_order: 0, modules: '', benefits: '', tags: '', robots: 'index,follow' },
    },
    inquiries: {
        title: 'Demandes entrantes', singular: 'demande', endpoint: '/inquiries', search: 'nom, e-mail, société ou message',
        columns: [['name', 'Nom'], ['company', 'Société'], ['type', 'Type'], ['requested_solution', 'Solution'], ['estimated_total', 'Estimation (DT)'], ['status', 'Statut']],
        fields: [
            { key: 'type', label: 'Type', type: 'select', required: true, options: [{ value: 'contact', label: 'Contact' }, { value: 'quote', label: 'Devis' }] },
            { key: 'name', label: 'Nom', required: true }, { key: 'email', label: 'E-mail', type: 'email', required: true },
            { key: 'phone', label: 'Téléphone' }, { key: 'company', label: 'Société' },
            { key: 'subject', label: 'Objet' }, { key: 'requested_solution', label: 'Solution demandée' },
            { key: 'activity', label: 'Activité / métier' },
            { key: 'company_size', label: 'Taille', type: 'select', options: [{ value: '', label: 'Non précisé' }, { value: 'solo', label: 'Indépendant' }, { value: '2-10', label: '2 à 10' }, { value: '11-50', label: '11 à 50' }, { value: '51-200', label: '51 à 200' }, { value: '200-plus', label: 'Plus de 200' }] },
            { key: 'user_count', label: 'Utilisateurs prévus', type: 'number' },
            { key: 'hosting_preference', label: 'Hébergement', type: 'select', options: [{ value: '', label: 'Non précisé' }, { value: 'included', label: 'Inclus AISYSPRO' }, { value: 'existing', label: 'Infrastructure existante' }, { value: 'undecided', label: 'À conseiller' }] },
            { key: 'desired_timeline', label: 'Délai', type: 'select', options: [{ value: '', label: 'Non précisé' }, { value: 'urgent', label: 'Urgent' }, { value: '1-3-months', label: '1 à 3 mois' }, { value: '3-6-months', label: '3 à 6 mois' }, { value: 'flexible', label: 'Flexible' }] },
            { key: 'budget_range', label: 'Budget', type: 'select', options: [{ value: '', label: 'Non précisé' }, { value: 'under-1000', label: 'Moins de 1 000 DT' }, { value: '1000-3000', label: '1 000 à 3 000 DT' }, { value: '3000-10000', label: '3 000 à 10 000 DT' }, { value: 'over-10000', label: 'Plus de 10 000 DT' }, { value: 'undecided', label: 'À définir' }] },
            { key: 'estimated_total', label: 'Estimation', type: 'number' },
            status([{ value: 'new', label: 'Nouvelle' }, { value: 'in_progress', label: 'En traitement' }, { value: 'closed', label: 'Clôturée' }]),
            { key: 'message', label: 'Message', type: 'textarea', wide: true, required: true },
        ],
        defaults: { type: 'contact', status: 'new' },
    },
    packs: {
        title: 'Packs & tarifs', singular: 'pack', endpoint: '/packs', search: 'nom ou description',
        columns: [['name', 'Nom'], ['price', 'Prix (DT)'], ['billing_period', 'Période'], ['featured', 'Mis en avant'], ['status', 'Statut']],
        fields: [
            { key: 'name', label: 'Nom', required: true }, { key: 'slug', label: 'Slug', required: true },
            { key: 'price', label: 'Prix', type: 'number' }, { key: 'billing_period', label: 'Période' },
            { key: 'description', label: 'Description', type: 'textarea', wide: true },
            { key: 'features', label: 'Fonctionnalités (une par ligne)', type: 'list', wide: true },
            status([{ value: 'draft', label: 'Brouillon' }, { value: 'published', label: 'Publié' }]),
            { key: 'featured', label: 'Mise en avant', type: 'checkbox' }, { key: 'sort_order', label: 'Ordre', type: 'number' },
        ],
        defaults: { status: 'draft', featured: false, sort_order: 0, features: '' },
    },
    'offer-options': {
        title: 'Options des offres', singular: 'option', endpoint: '/offer-options', search: 'nom ou description',
        columns: [['name', 'Nom'], ['price', 'Prix (DT)'], ['sort_order', 'Ordre'], ['status', 'Statut']],
        fields: [
            { key: 'name', label: 'Nom', required: true }, { key: 'slug', label: 'Slug', required: true },
            { key: 'price', label: 'Prix', type: 'number', required: true },
            { key: 'description', label: 'Description', type: 'textarea', wide: true },
            status([{ value: 'draft', label: 'Brouillon' }, { value: 'published', label: 'Publié' }]),
            { key: 'sort_order', label: 'Ordre', type: 'number', required: true },
        ],
        defaults: { status: 'draft', price: 0, sort_order: 0 },
    },
    faqs: {
        title: 'Questions fréquentes', singular: 'question', endpoint: '/faqs', search: 'question, réponse ou catégorie',
        columns: [['question', 'Question'], ['category', 'Catégorie'], ['sort_order', 'Ordre'], ['status', 'Statut']],
        fields: [
            { key: 'question', label: 'Question', required: true, wide: true }, { key: 'answer', label: 'Réponse', type: 'textarea', required: true, wide: true },
            { key: 'category', label: 'Catégorie' }, status([{ value: 'draft', label: 'Brouillon' }, { value: 'published', label: 'Publié' }]),
            { key: 'sort_order', label: 'Ordre', type: 'number' },
        ],
        defaults: { status: 'draft', sort_order: 0 },
    },
    pages: {
        title: 'Pages publiques', singular: 'page', endpoint: '/pages', search: 'titre, URL ou contenu',
        columns: [['title', 'Titre'], ['slug', 'URL'], ['published_at', 'Publication'], ['status', 'Statut']],
        fields: [
            { key: 'title', label: 'Titre', required: true }, { key: 'slug', label: 'Slug', required: true },
            { key: 'excerpt', label: 'Extrait', type: 'textarea', wide: true }, { key: 'content', label: 'Contenu', type: 'textarea', wide: true },
            status([{ value: 'draft', label: 'Brouillon' }, { value: 'published', label: 'Publié' }]),
            { key: 'published_at', label: 'Date de publication', type: 'datetime-local' },
            { key: 'meta_title', label: 'Titre SEO' }, { key: 'meta_description', label: 'Description SEO', type: 'textarea', wide: true },
            { key: 'canonical_url', label: 'URL canonique', type: 'url', wide: true },
            { key: 'og_title', label: 'Titre Open Graph' }, { key: 'og_description', label: 'Description Open Graph', type: 'textarea', wide: true },
            { key: 'og_image', label: 'Image Open Graph', type: 'url', wide: true },
            { key: 'robots', label: 'Indexation', type: 'select', required: true, options: [{ value: 'index,follow', label: 'Indexer et suivre' }, { value: 'noindex,nofollow', label: 'Ne pas indexer' }] },
        ],
        defaults: { status: 'draft', robots: 'index,follow' },
    },
    testimonials: {
        title: 'Témoignages', singular: 'témoignage', endpoint: '/testimonials', search: 'nom, société ou contenu',
        columns: [['name', 'Nom'], ['company', 'Société'], ['role', 'Fonction'], ['rating', 'Note'], ['status', 'Statut']],
        fields: [
            { key: 'name', label: 'Nom', required: true }, { key: 'company', label: 'Société' },
            { key: 'role', label: 'Fonction' }, { key: 'content', label: 'Témoignage', type: 'textarea', required: true, wide: true },
            { key: 'rating', label: 'Note', type: 'number', required: true },
            status([{ value: 'draft', label: 'Brouillon' }, { value: 'published', label: 'Publié' }, { value: 'hidden', label: 'Masqué' }]),
            { key: 'sort_order', label: 'Ordre', type: 'number' },
        ],
        defaults: { status: 'draft', rating: 5, sort_order: 0 },
    },
};
