<script setup>
import { onMounted } from 'vue';
import PublicLayout from '../../layouts/PublicLayout.vue';
import PageHero from '../../components/PageHero.vue';
import ScaleCta from '../../components/ScaleCta.vue';
import { useSeo } from '../../composables/useSeo';
onMounted(() => useSeo('À propos d’AISYSPRO', 'AISYSPRO transforme les processus métier en solutions simples, robustes et évolutives.'));
</script>

<template><PublicLayout><main><PageHero label="AISYSPRO · Une solution AISYSNEXT" title="La technologie utile." accent="L’expertise proche du terrain." description="Nous transformons les processus métier en solutions simples à utiliser, solides à exploiter et capables d’évoluer avec l’entreprise." />
    <section class="new-section story-section"><div class="new-heading"><span class="eyebrow-new">Notre conviction</span><h2>Un bon outil ne vous impose pas sa logique.<br><em>Il épouse la vôtre.</em></h2></div><div class="story-copy"><p>AISYSPRO, solution portée par AISYSNEXT, accompagne les professionnels, PME et startups dans la conception de systèmes métier réellement adaptés. Nous réunissons conseil, UX, développement, CRM, web et infrastructure pour éviter les ruptures de responsabilité.</p><p>Notre équipe travaille au croisement de la compréhension métier et de l’exécution technique : chaque écran doit répondre à une action, chaque automatisation à un gain mesurable.</p></div><div class="story-numbers"><article><b>360°</b><span>Conception, développement, hébergement et suivi</span></article><article><b>Agile</b><span>Des sprints courts, démontrables et testables</span></article><article><b>Local</b><span>Une équipe proche, des standards internationaux</span></article><article><b>Durable</b><span>Une architecture pensée pour évoluer</span></article></div></section>
    <section class="method-section"><div class="new-heading light"><span class="eyebrow-new light">Nos principes</span><h2>Ce qui guide<br><em>chaque décision produit.</em></h2></div><div class="principles-grid"><article v-for="(item,index) in [['Clarté','Des périmètres, prix et responsabilités visibles.'],['Utilité','Chaque fonction répond à un besoin opérationnel.'],['Qualité','Tests croisés client, QA et expert métier.'],['Évolutivité','Des modules et intégrations activables progressivement.'],['Sécurité','Droits, sauvegardes et traçabilité dès la conception.'],['Partenariat','Un interlocuteur qui suit le produit dans la durée.']]" :key="item[0]"><span>0{{ index+1 }}</span><h3>{{ item[0] }}</h3><p>{{ item[1] }}</p></article></div></section>
    <section class="new-section promise-section"><div class="new-heading"><span class="eyebrow-new">Une promesse vérifiable</span><h2>Transparence commerciale,<br><em>maîtrise technique.</em></h2></div><div class="promise-grid"><article><h3>Prix visibles</h3><p>Le pack et chaque option sont affichés avant la demande.</p></article><article><h3>Sans licence cachée</h3><p>Le socle convenu est cadré sans licence récurrente AISYSPRO cachée.</p></article><article><h3>SAV pendant un an</h3><p>L’accompagnement prévu dans l’offre couvre douze mois.</p></article><article><h3>Données maîtrisées</h3><p>Un hébergement sur les serveurs du client peut être étudié selon ses contraintes.</p></article></div></section>
    <ScaleCta /></main></PublicLayout></template>
